alter table deacons.deacons.liturgies
    alter column id
        set generated by default;

INSERT INTO deacons.deacons.liturgies (id, liturgy_name)
VALUES (1, 'قداس الميلاد'), (2,'قداس الغطاس'), (3,'قداس القيامة'), (4,'قداس جمعة ختام الصوم'), (5,'قداس أحد الشعانين'), (6,'قداس خميس العهد'), (7,'البصخة'), (8,'قداس سبت الفرح');