alter table deacons.deacons.skills
    alter column id
        set generated by default;

INSERT INTO deacons.deacons.skills (id, skill)
VALUES (1,'خدمة هيكل (قداس)'), (2,'خدمة هيكل (رفع بخور)'), (3,'مزمور قبطي'), (4,'نبوات قبطي'), (5,'إنجيل عربي بصخة'), (6,'بولس قبطي'), (7,'كاثوليكون قبطي'), (8,'إبركسيس قبطي');

