alter table deacons.deacons.events
    alter column id
        set generated by default;

INSERT INTO deacons.deacons.events (id, event_name, weight)
VALUES (1,'خدمة قداس عيد كبير', 1), (2,'رفع بخور قداس عيد', 1), (3,'خدمة قداس عيد صغير', 1), (4,'مزمور بصخة', 1),(5,'إنجيل بصخة عربي', 1), (6,'قراءة قبطي عيد', 1);

