definitions:
  db.GetAllHistoryServiceRow:
    properties:
      date:
        type: string
      deaconID:
        format: int64
        type: integer
      eslID:
        format: int32
        type: integer
      eventName:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      liturgyName:
        type: string
      skill:
        type: string
    type: object
  db.GetDependantSkillsRow:
    properties:
      eslID:
        format: int32
        type: integer
      skill:
        type: string
      skillID:
        format: int32
        type: integer
    type: object
  db.GetEventsRow:
    properties:
      eventName:
        type: string
      id:
        format: int32
        type: integer
    type: object
  db.GetHistoryServiceByDeaconIdRow:
    properties:
      date:
        type: string
      eventName:
        type: string
      id:
        format: int32
        type: integer
      liturgyName:
        type: string
      skill:
        type: string
    type: object
  db.GetLiturgiesRow:
    properties:
      id:
        format: int32
        type: integer
      liturgyName:
        type: string
    type: object
  db.GetSkillsRow:
    properties:
      id:
        format: int32
        type: integer
      skill:
        type: string
    type: object
  db.GetSuggestionRow:
    properties:
      firstName:
        type: string
      id:
        format: int64
        type: integer
      lastName:
        type: string
      score:
        format: float64
        type: number
    type: object
  payload.Attendance:
    properties:
      date:
        type: string
      esl_id:
        type: integer
    required:
    - date
    - esl_id
    type: object
  payload.BulkAttendance:
    properties:
      date:
        type: string
      deacon_id:
        items:
          type: integer
        type: array
      esl_id:
        type: integer
      override:
        type: boolean
    required:
    - date
    - deacon_id
    - esl_id
    type: object
  payload.Deacon:
    properties:
      address:
        type: string
      country:
        type: string
      deacon_rank:
        type: integer
      dob:
        type: string
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      phone:
        type: string
      skills:
        items:
          $ref: '#/definitions/payload.DeaconSkill'
        type: array
    required:
    - country
    - deacon_rank
    - first_name
    - last_name
    type: object
  payload.DeaconSkill:
    properties:
      score:
        type: integer
      skill_id:
        type: integer
    required:
    - score
    - skill_id
    type: object
  payload.RefreshPayload:
    properties:
      refresh_token:
        type: string
      user_id:
        type: integer
    required:
    - refresh_token
    - user_id
    type: object
  payload.User:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  response.LoginResponse:
    properties:
      refresh_token:
        example: GciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
      user_id:
        example: 1
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  title: Sharobim Deacons API
  version: "1.0"
paths:
  /attendance/deacon/{id}:
    delete:
      description: Delete Service History to a Deacon
      parameters:
      - description: Deacon ID
        in: path
        name: id
        required: true
        type: integer
      - description: Attendance
        in: body
        name: payload.Attendance
        required: true
        schema:
          $ref: '#/definitions/payload.Attendance'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      tags:
      - Attendance
    get:
      description: Get All Services done by a deacon
      parameters:
      - description: Deacon ID
        in: path
        name: id
        required: true
        type: integer
      - description: Page Number
        in: query
        name: page
        required: true
        type: string
      - description: Number of elements per page
        in: query
        name: limit
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.GetHistoryServiceByDeaconIdRow'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      tags:
      - Attendance
  /attendance/deacon/bulk:
    post:
      description: Add Service History to a Deacon
      parameters:
      - description: Attendance
        in: body
        name: payload.BulkAttendance
        required: true
        schema:
          $ref: '#/definitions/payload.BulkAttendance'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      tags:
      - Attendance
  /attendance/history:
    get:
      description: Get Service History in our church
      parameters:
      - description: Page Number
        in: query
        name: page
        required: true
        type: string
      - description: Number of elements per page
        in: query
        name: limit
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.GetAllHistoryServiceRow'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      tags:
      - Attendance
  /attendance/suggestion:
    get:
      description: Get Suggestion for a specific skill
      parameters:
      - description: Event Skill Liturgy ID
        in: query
        name: eslId
        required: true
        type: string
      - description: Page Number
        in: query
        name: page
        required: true
        type: string
      - description: Number of elements per page
        in: query
        name: limit
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.GetSuggestionRow'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      tags:
      - Attendance
  /deacons/:
    get:
      description: Lists All Deacons Paginated
      parameters:
      - description: Page Number
        in: query
        name: page
        type: string
      - description: Number of elements per page
        in: query
        name: limit
        type: string
      - description: name, date_of_birth, country, deacon_rank_id
        in: query
        name: sort
        type: string
      - description: ASC OR DESC
        in: query
        name: direction
        type: string
      - description: name, country, deacon_rank_id
        in: query
        name: filter_field
        type: string
      - description: The value of the filtered selection
        in: query
        name: filter_value
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties:
                type: string
              type: object
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      tags:
      - Deacons
    post:
      description: Create a deacon profile
      parameters:
      - description: Creation
        in: body
        name: payload.Deacon
        required: true
        schema:
          $ref: '#/definitions/payload.Deacon'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      tags:
      - Deacons
  /deacons/{id}:
    delete:
      description: Deletes a Deacon and his skills
      parameters:
      - description: Deacon ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      tags:
      - Deacons
    get:
      description: Get A Detailed info of a specific deacon
      parameters:
      - description: Deacon ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      tags:
      - Deacons
    put:
      description: Update a deacon and its skills
      parameters:
      - description: Deacon ID
        in: path
        name: id
        required: true
        type: integer
      - description: Creation
        in: body
        name: payload.Deacon
        required: true
        schema:
          $ref: '#/definitions/payload.Deacon'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      tags:
      - Deacons
  /deacons/ranks:
    get:
      description: Lists All Deacons Ranks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties:
                type: string
              type: object
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      tags:
      - Deacons
  /events/{liturgy_id}:
    get:
      description: Lists All Skills
      parameters:
      - description: Liturgy ID
        in: path
        name: liturgy_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.GetEventsRow'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      tags:
      - Events
  /liturgy:
    get:
      description: Lists All Liturgies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.GetLiturgiesRow'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      tags:
      - Liturgies
  /skills:
    get:
      description: Lists All Skills
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.GetSkillsRow'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      tags:
      - Skills
  /skills/{liturgy_id}/{event_id}:
    get:
      description: Lists All Skills depending on liturgy and event
      parameters:
      - description: Liturgy ID
        in: path
        name: liturgy_id
        required: true
        type: integer
      - description: Event ID
        in: path
        name: event_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.GetDependantSkillsRow'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      tags:
      - Skills
  /user/login:
    post:
      consumes:
      - application/json
      description: Logs In The User
      parameters:
      - description: Logging
        in: body
        name: payload.User
        required: true
        schema:
          $ref: '#/definitions/payload.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.LoginResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
      tags:
      - User
  /user/refresh:
    post:
      consumes:
      - application/json
      description: send refresh token to get new JWT Token
      parameters:
      - description: Refreshing
        in: body
        name: payload.RefreshPayload
        required: true
        schema:
          $ref: '#/definitions/payload.RefreshPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.LoginResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
      tags:
      - User
  /user/register:
    post:
      consumes:
      - application/json
      description: Creates a User for the application
      parameters:
      - description: Creation
        in: body
        name: payload.User
        required: true
        schema:
          $ref: '#/definitions/payload.User'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.LoginResponse'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      tags:
      - User
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
