// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: attendance_history.sql

package db

import (
	"context"
	"time"
)

const addHistoryService = `-- name: AddHistoryService :exec
INSERT INTO deacons.deacons.attendances (deacon_id, event_skill_liturgy_id, date) Values($1,$2,$3)
`

type AddHistoryServiceParams struct {
	DeaconID            int64
	EventSkillLiturgyID int32
	Date                time.Time
}

func (q *Queries) AddHistoryService(ctx context.Context, arg AddHistoryServiceParams) error {
	_, err := q.db.ExecContext(ctx, addHistoryService, arg.DeaconID, arg.EventSkillLiturgyID, arg.Date)
	return err
}

const deleteHistoryService = `-- name: DeleteHistoryService :exec
DELETE from deacons.deacons.attendances WHERE deacon_id= $1 and event_skill_liturgy_id= $2 and date=$3
`

type DeleteHistoryServiceParams struct {
	DeaconID            int64
	EventSkillLiturgyID int32
	Date                time.Time
}

func (q *Queries) DeleteHistoryService(ctx context.Context, arg DeleteHistoryServiceParams) error {
	_, err := q.db.ExecContext(ctx, deleteHistoryService, arg.DeaconID, arg.EventSkillLiturgyID, arg.Date)
	return err
}

const getAllHistoryService = `-- name: GetAllHistoryService :many
SELECT
    esl.id as esl_id,
    skl.skill,
    evnt.event_name,
    lit.liturgy_name,
    att.date,
    deacon.first_name,
    deacon.last_name,
    deacon.id as deacon_id
FROM deacons.deacons.deacons deacon
        Join deacons.deacons.attendances att on deacon.id = att.deacon_id
         Join deacons.deacons.event_skill_liturgy esl on att.event_skill_liturgy_id = esl.id
         Join deacons.deacons.liturgies lit on esl.liturgy_id = lit.id
         Join deacons.deacons.events evnt on esl.event_id = evnt.id
         Join deacons.deacons.skills skl on esl.skill_id = skl.id
ORDER BY att.date DESC
OFFSET $1
    LIMIT $2
`

type GetAllHistoryServiceParams struct {
	Offset int32
	Limit  int32
}

type GetAllHistoryServiceRow struct {
	EslID       int32
	Skill       string
	EventName   string
	LiturgyName string
	Date        time.Time
	FirstName   string
	LastName    string
	DeaconID    int64
}

func (q *Queries) GetAllHistoryService(ctx context.Context, arg GetAllHistoryServiceParams) ([]GetAllHistoryServiceRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllHistoryService, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllHistoryServiceRow
	for rows.Next() {
		var i GetAllHistoryServiceRow
		if err := rows.Scan(
			&i.EslID,
			&i.Skill,
			&i.EventName,
			&i.LiturgyName,
			&i.Date,
			&i.FirstName,
			&i.LastName,
			&i.DeaconID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHistoryServiceByDeaconId = `-- name: GetHistoryServiceByDeaconId :many
SELECT
    esl.id,
    skl.skill,
    evnt.event_name,
    lit.liturgy_name,
    att.date
FROM deacons.deacons.attendances att
         Join deacons.deacons.event_skill_liturgy esl on att.event_skill_liturgy_id = esl.id
         Join deacons.deacons.liturgies lit on esl.liturgy_id = lit.id
         Join deacons.deacons.events evnt on esl.event_id = evnt.id
         Join deacons.deacons.skills skl on esl.skill_id = skl.id
WHERE att.deacon_id = $1
ORDER BY att.date DESC
OFFSET $2
    LIMIT $3
`

type GetHistoryServiceByDeaconIdParams struct {
	DeaconID int64
	Offset   int32
	Limit    int32
}

type GetHistoryServiceByDeaconIdRow struct {
	ID          int32
	Skill       string
	EventName   string
	LiturgyName string
	Date        time.Time
}

func (q *Queries) GetHistoryServiceByDeaconId(ctx context.Context, arg GetHistoryServiceByDeaconIdParams) ([]GetHistoryServiceByDeaconIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getHistoryServiceByDeaconId, arg.DeaconID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHistoryServiceByDeaconIdRow
	for rows.Next() {
		var i GetHistoryServiceByDeaconIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Skill,
			&i.EventName,
			&i.LiturgyName,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSuggestion = `-- name: GetSuggestion :many
SELECT
    d.id,
    d.first_name,
    d.last_name,
    COALESCE(
            SUM(
                    e.weight
                        * POWER(
                            0.5,
                            EXTRACT(YEAR FROM CURRENT_DATE)
                                - a.year
                          )
            ),
            0
    )::DOUBLE PRECISION AS score
FROM deacons.deacons.deacons d
         JOIN deacons.deacons.deacon_skill ds
              ON d.id = ds.deacon_id
         JOIN deacons.deacons.event_skill_liturgy esl_filter
              ON esl_filter.id = $1
         LEFT JOIN deacons.deacons.attendances a
                   ON d.id = a.deacon_id
                       AND a.date >= date_trunc('year', CURRENT_DATE) - INTERVAL '4 years'
         LEFT JOIN deacons.deacons.event_skill_liturgy esl
                   ON a.event_skill_liturgy_id = esl.id
         LEFT JOIN deacons.deacons.events e
                   ON esl.event_id = e.id
WHERE ds.skill_id = esl_filter.skill_id
  AND ds.score >= esl_filter.minimum_score
GROUP BY d.id, d.first_name, d.last_name
ORDER BY score
OFFSET $2
    LIMIT $3
`

type GetSuggestionParams struct {
	Eslid   int32
	POffset int32
	PLimit  int32
}

type GetSuggestionRow struct {
	ID        int64
	FirstName string
	LastName  string
	Score     float64
}

func (q *Queries) GetSuggestion(ctx context.Context, arg GetSuggestionParams) ([]GetSuggestionRow, error) {
	rows, err := q.db.QueryContext(ctx, getSuggestion, arg.Eslid, arg.POffset, arg.PLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSuggestionRow
	for rows.Next() {
		var i GetSuggestionRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
