// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deacon.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getDeaconById = `-- name: GetDeaconById :one
SELECT
    d.first_name,
    d.last_name,
    d.date_of_birth,
    d.address,
    d.email,
    d.phone_number,
    d.country,
    dr.rank_name
FROM deacons.deacons.deacons d
Join deacons.deacons.deacon_ranks dr on d.deacon_rank_id=dr.id
WHERE d.id = $1
`

type GetDeaconByIdRow struct {
	FirstName   string
	LastName    string
	DateOfBirth sql.NullTime
	Address     sql.NullString
	Email       sql.NullString
	PhoneNumber sql.NullString
	Country     string
	RankName    string
}

func (q *Queries) GetDeaconById(ctx context.Context, id int64) (GetDeaconByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getDeaconById, id)
	var i GetDeaconByIdRow
	err := row.Scan(
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Address,
		&i.Email,
		&i.PhoneNumber,
		&i.Country,
		&i.RankName,
	)
	return i, err
}

const getHistoryServiceByDeaconId = `-- name: GetHistoryServiceByDeaconId :many
SELECT
    skl.skill,
    evnt.event_name,
    lit.liturgy_name,
    att.date
FROM deacons.deacons.attendances att
         Join deacons.deacons.event_skill_liturgy esl on att.event_skill_liturgy_id = esl.id
         Join deacons.deacons.liturgies lit on esl.liturgy_id = lit.id
         Join deacons.deacons.events evnt on esl.event_id = evnt.id
         Join deacons.deacons.skills skl on esl.skill_id = skl.id
WHERE att.deacon_id = $1
OFFSET $2
LIMIT $3
`

type GetHistoryServiceByDeaconIdParams struct {
	DeaconID int64
	Offset   int32
	Limit    int32
}

type GetHistoryServiceByDeaconIdRow struct {
	Skill       string
	EventName   string
	LiturgyName string
	Date        time.Time
}

func (q *Queries) GetHistoryServiceByDeaconId(ctx context.Context, arg GetHistoryServiceByDeaconIdParams) ([]GetHistoryServiceByDeaconIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getHistoryServiceByDeaconId, arg.DeaconID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHistoryServiceByDeaconIdRow
	for rows.Next() {
		var i GetHistoryServiceByDeaconIdRow
		if err := rows.Scan(
			&i.Skill,
			&i.EventName,
			&i.LiturgyName,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
