// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: event_skill_liturgy.sql

package db

import (
	"context"
	"time"
)

const getEventSkillLiturgy = `-- name: GetEventSkillLiturgy :one
SELECT
    id, liturgy_id, event_id, skill_id, minimum_score, capacity
FROM deacons.deacons.event_skill_liturgy esl
WHERE esl.id=$1
`

type GetEventSkillLiturgyRow struct {
	ID           int32
	LiturgyID    int32
	EventID      int32
	SkillID      int32
	MinimumScore int32
	Capacity     int32
}

func (q *Queries) GetEventSkillLiturgy(ctx context.Context, id int32) (GetEventSkillLiturgyRow, error) {
	row := q.db.QueryRowContext(ctx, getEventSkillLiturgy, id)
	var i GetEventSkillLiturgyRow
	err := row.Scan(
		&i.ID,
		&i.LiturgyID,
		&i.EventID,
		&i.SkillID,
		&i.MinimumScore,
		&i.Capacity,
	)
	return i, err
}

const getRemainingEventSkillLiturgyCapacity = `-- name: GetRemainingEventSkillLiturgyCapacity :one
SELECT
    esl.capacity - count(deacon_id)
FROM deacons.deacons.event_skill_liturgy esl left join deacons.deacons.attendances att on esl.id = att.event_skill_liturgy_id
    and EXTRACT(YEAR FROM att.date) = EXTRACT(YEAR FROM $1::date)
WHERE esl.id = $2
GROUP BY esl.id
`

type GetRemainingEventSkillLiturgyCapacityParams struct {
	ServiceDate time.Time
	Eslid       int32
}

func (q *Queries) GetRemainingEventSkillLiturgyCapacity(ctx context.Context, arg GetRemainingEventSkillLiturgyCapacityParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getRemainingEventSkillLiturgyCapacity, arg.ServiceDate, arg.Eslid)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
