// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: event_skill_liturgy.sql

package db

import (
	"context"
)

const getEventSkillLiturgy = `-- name: GetEventSkillLiturgy :one
SELECT
    id, liturgy_id, event_id, skill_id, minimum_score
FROM deacons.deacons.event_skill_liturgy esl
WHERE esl.id=$1
`

type GetEventSkillLiturgyRow struct {
	ID           int32
	LiturgyID    int32
	EventID      int32
	SkillID      int32
	MinimumScore int32
}

func (q *Queries) GetEventSkillLiturgy(ctx context.Context, id int32) (GetEventSkillLiturgyRow, error) {
	row := q.db.QueryRowContext(ctx, getEventSkillLiturgy, id)
	var i GetEventSkillLiturgyRow
	err := row.Scan(
		&i.ID,
		&i.LiturgyID,
		&i.EventID,
		&i.SkillID,
		&i.MinimumScore,
	)
	return i, err
}
