// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type DeaconsAttendance struct {
	DeaconID            int64
	EventSkillLiturgyID int32
	Date                time.Time
	Year                sql.NullInt32
}

type DeaconsDeacon struct {
	ID           int64
	FirstName    string
	LastName     string
	Address      sql.NullString
	Email        sql.NullString
	PhoneNumber  sql.NullString
	DateOfBirth  sql.NullTime
	Country      string
	DeaconRankID int32
}

type DeaconsDeaconRank struct {
	ID       int32
	RankName string
}

type DeaconsDeaconRessama struct {
	DeaconID     int64
	DeaconRankID int32
	Date         time.Time
}

type DeaconsDeaconSkill struct {
	DeaconID int64
	SkillID  int32
	Score    int32
}

type DeaconsEvent struct {
	ID        int32
	EventName string
	Weight    string
}

type DeaconsEventSkillLiturgy struct {
	ID           int32
	LiturgyID    int32
	EventID      int32
	SkillID      int32
	MinimumScore int32
	Capacity     int32
}

type DeaconsLiturgy struct {
	ID          int32
	LiturgyName string
}

type DeaconsRole struct {
	ID   int32
	Role string
}

type DeaconsSkill struct {
	ID    int32
	Skill string
}

type DeaconsUser struct {
	ID       int64
	Email    string
	Password string
}

type DeaconsUserRole struct {
	UserID int64
	RoleID int32
}
