// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: skills.sql

package db

import (
	"context"
)

const getSkills = `-- name: GetSkills :many
SELECT
    id, skill
FROM deacons.deacons.skills
`

type GetSkillsRow struct {
	ID    int32
	Skill string
}

func (q *Queries) GetSkills(ctx context.Context) ([]GetSkillsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSkillsRow
	for rows.Next() {
		var i GetSkillsRow
		if err := rows.Scan(&i.ID, &i.Skill); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
