// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package db

import (
	"context"
)

const assignRole = `-- name: AssignRole :exec
INSERT INTO deacons.deacons.user_role (user_id, role_id)
VALUES ($1, $2)
`

type AssignRoleParams struct {
	UserID int64
	RoleID int32
}

func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) error {
	_, err := q.db.ExecContext(ctx, assignRole, arg.UserID, arg.RoleID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO deacons.deacons.users (email, password)
VALUES ($1, $2)
RETURNING id
`

type CreateUserParams struct {
	Email    string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Password)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getRoles = `-- name: GetRoles :many
SELECT id, role
FROM deacons.deacons.roles
`

type GetRolesRow struct {
	ID   int32
	Role string
}

func (q *Queries) GetRoles(ctx context.Context) ([]GetRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRolesRow
	for rows.Next() {
		var i GetRolesRow
		if err := rows.Scan(&i.ID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    u.id,
    u.email,
    u.password,
    STRING_AGG(r.role, ',') AS roles
FROM deacons.deacons.users u
         JOIN deacons.deacons.user_role ur ON u.id = ur.user_id
         JOIN deacons.deacons.roles r ON r.id = ur.role_id
WHERE u.email = $1
GROUP BY u.id, u.email, u.password
`

type GetUserByEmailRow struct {
	ID       int64
	Email    string
	Password string
	Roles    []byte
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Roles,
	)
	return i, err
}
